version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Rome"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/.github/scripts"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
      timezone: "Europe/Rome"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      python-tooling-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  # - package-ecosystem: "pre-commit"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #     day: "monday"
  #     time: "09:00"
  #     timezone: "Europe/Rome"
  #   open-pull-requests-limit: 5
  #   labels:
  #     - "dependencies"
  #     - "pre-commit"
  #   commit-message:
  #     prefix: "deps"
  #     include: "scope"
  #   groups:
  #     pre-commit-minor-patch:
  #       patterns:
  #         - "*"
  #       update-types:
  #         - "minor"
  #         - "patch"
