name: Validate Copilot Customizations

on:
  pull_request:
    paths:
      - ".github/**"
  push:
    branches:
      - main
    paths:
      - ".github/**"

permissions:
  contents: read

concurrency:
  group: validate-copilot-customizations-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate Files
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Lint validator script
        run: |
          bash -n .github/scripts/validate-copilot-customizations.sh
          shellcheck -s bash .github/scripts/validate-copilot-customizations.sh

      - name: Validate copilot customizations
        run: .github/scripts/validate-copilot-customizations.sh
