name: Validate Copilot Customizations

on:
  pull_request:
    paths:
      - ".github/**"
  push:
    branches:
      - main
    paths:
      - ".github/**"

permissions:
  contents: read

concurrency:
  group: validate-copilot-customizations-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate Files
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Validate copilot customizations
        run: .github/scripts/validate-copilot-customizations.sh
