# Scopo: installa dipendenze Python per i controlli PR
name: "🐍 Build & Test Python"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
  push:
    branches:
      - main

permissions:
  contents: read
  actions: write

# Evita di eseguire più job contemporaneamente per lo stesso riferimento (es. commit su PR)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-python:

    name: "build python"
    runs-on: "ubuntu-22.04"

    steps:
      - name: checkout
        # https://github.com/actions/checkout/releases/tag/v4.0.0
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2

      - name: setup-python
        # https://github.com/actions/setup-python/releases/tag/v5.1.0
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version-file: ".python-version"
          cache: 'pip' # Abilita il caching delle dipendenze per velocizzare le esecuzioni successive

      - name: install-anomaly-deps
        run: pip3 install --require-hashes --requirement azure/anomaly_detection/requirements-anomaly.txt

      - name: install-azure-rel-deps
        run: pip3 install --require-hashes --requirement azure/rel/requirements.txt

      - name: install-aws-deps
        run: pip3 install --requirement aws/requirements.txt
