# Scopo: rilevamento anomalie costi Azure/SES
name: "👀 Detect cost anomalies"

env:
  AWS_REGION: eu-south-1
  IAM_ROLE: arn:aws:iam::155090677366:role/GitHubActionSesRole

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:

  detect-anomalies:

    name: "detect-anomalies"
    runs-on: "ubuntu-22.04"
    environment: prod

    steps:
      - name: checkout
        # https://github.com/actions/checkout/releases/tag/v4.0.0
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2

      - name: setup-python
        # https://github.com/actions/setup-python/releases/tag/v5.1.0
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version-file: ".python-version"

      - name: install-py-deps
        run: pip3 install -r azure/anomaly_detection/requirements-anomaly.txt


      - name: Login to Azure
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: "anomaly-cost-detection"
        id: "anomaly-cost-detection"
        run: python3 azure/anomaly_detection/anomaly_detection_script.py
